#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts none /dev/pts
mkdir /mnt
#mount -t nfs -o proto=tcp,nolock,port=2049 141.212.11.162:/export /mnt
ifconfig lo 127.0.0.1
# ifconfig eth0 172.17.0.199

# Auto-start the SensEye Server
#/load_stonyman.sh
#/senseye_serv

