# Makefile for an A2F-Linux project

export SENSEYE_DIR = $(shell pwd)

# This project's name
SAMPLE		:= senseye_proj

# Custom applcations subdirectories that this project
# needs to build. Edit this list as appropriate for your application.
CUSTOM_APPS	:= ../stonyman ../senseye_serv

# Include Make rules applicable to all projects
include ${INSTALL_ROOT}/projects/Rules.make
